INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='上海' ), N'0986', N'SYSTEM', '20150831 19:05:51.457', N'', NULL, 1, 'ec1bb06e', N'上海分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='深圳' ), N'1086', N'SYSTEM', '20150831 19:05:51.460', N'', NULL, 1, '3257f5b0', N'深圳分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='北京' ), N'1186', N'SYSTEM', '20150831 19:05:51.467', N'', NULL, 1, '71e6608f', N'北京分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='JS New City' ), N'1286', N'SYSTEM', '20150831 19:05:51.470', N'', NULL, 1, 'c017625d', N'江苏分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='苏州' ), N'1286', N'SYSTEM', '20150831 19:05:51.470', N'', NULL, 1, 'c017625d', N'江苏分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='东区' ), N'2586', N'SYSTEM', '20150831 19:05:51.480', N'', NULL, 1, '93711271', N'广东分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='中区' ), N'2586', N'SYSTEM', '20150831 19:05:51.480', N'', NULL, 1, '93711271', N'广东分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='西区' ), N'2586', N'SYSTEM', '20150831 19:05:51.480', N'', NULL, 1, '93711271', N'广东分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='西区' ), N'2686', N'SYSTEM', '20150831 19:05:51.490', N'', NULL, 1, 'c0ed5d5e', N'佛山支公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='东区' ), N'2786', N'SYSTEM', '20150831 19:05:51.497', N'', NULL, 1, '2952f592', N'江门支公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='东区' ), N'2886', N'SYSTEM', '20150831 19:05:51.520', N'', NULL, 1, '9a9d4900', N'东莞支公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='东区' ), N'2786', N'SYSTEM', '20150831 19:05:51.497', N'', NULL, 1, '78120d8e', N'江门支公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='10Sep15_DI' ), N'12345', N'Admin', '20150910 14:33:16.127', N'', NULL, 1, 'b83315de', N'10Sep15_BR', 2);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME='10Sep15_DI' ), N'2586', N'SYSTEM', '20150831 19:05:51.480', N'', NULL, 1, '2574c5cc', N'广东分公司', 0);


