INSERT INTO [dbo].[T_BU] ( [BU_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( N'上海', N'', NULL, N'Admin', '20150831 21:20:20.260', 1, '2503f200', 0);

INSERT INTO [dbo].[T_BU] ( [BU_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( N'北京', N'', NULL, N'Admin', '20150831 21:20:55.390', 1, 'b02951e2', 0);

INSERT INTO [dbo].[T_BU] ( [BU_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( N'深圳', N'', NULL, N'Admin', '20150831 21:21:07.097', 1, 'a79afaad', 0);

INSERT INTO [dbo].[T_BU] ( [BU_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( N'广东', N'', NULL, N'Admin', '20150831 21:21:18.310', 1, '6feb1997', 0);

INSERT INTO [dbo].[T_BU] ( [BU_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( N'江苏', N'', NULL, N'Admin', '20150831 21:21:31.223', 1, '7dfc46d3', 0);

INSERT INTO [dbo].[T_BU] ( [BU_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( N'10Sep15_BU', N'Admin', '20150910 14:30:00.790', N'', NULL, 1, 'e2173dec', 2);


INSERT INTO [dbo].[T_DISTRICT] ([BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( (SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'上海' ), N'上海', N'SYSTEM', '20150831 19:05:51.390', N'Admin', '20150831 21:22:03.603', 1, '477d61d7', 0);

INSERT INTO [dbo].[T_DISTRICT] ([BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( (SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'北京' ), N'北京', N'SYSTEM', '20150831 19:05:51.397', N'Admin', '20150831 21:22:19.933', 1, 'e05da92b', 0);

INSERT INTO [dbo].[T_DISTRICT] ([BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( (SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'深圳' ), N'深圳', N'SYSTEM', '20150831 19:05:51.403', N'Admin', '20150831 21:22:38.460', 1, '0c3ce014', 0);

INSERT INTO [dbo].[T_DISTRICT] ([BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( (SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'广东' ), N'中区', N'SYSTEM', '20150831 19:05:51.410', N'Admin', '20150831 21:22:59.677', 1, 'cf115983', 0);

INSERT INTO [dbo].[T_DISTRICT] ([BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ((SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'江苏' ), N'苏州', N'SYSTEM', '20150831 19:05:51.417', N'Admin', '20150831 21:23:19.333', 1, '2e6e8a92', 0);

INSERT INTO [dbo].[T_DISTRICT] ([BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( (SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'广东' ), N'西区', N'Admin', '20150831 21:23:39.673', N'', NULL, 1, '5c026be8', 0);

INSERT INTO [dbo].[T_DISTRICT] ([BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ((SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'广东' ), N'东区', N'Admin', '20150831 21:24:07.917', N'', NULL, 1, '53ac140f', 0);

INSERT INTO [dbo].[T_DISTRICT] ( [BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( (SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'江苏' ), N'JS New City', N'Admin', '20150831 21:25:06.837', N'', NULL, 1, 'd2721123', 0);

INSERT INTO [dbo].[T_DISTRICT] ([BU_CODE], [DISTRICT_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [ORDERCODE])
VALUES ( (SELECT BU_CODE FROM T_BU WHERE BU_NAME=N'10Sep15_BU' ), N'10Sep15_DI', N'Admin', '20150910 14:31:46.920', N'', NULL, 1, 'c533d422', 2);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'上海' ), N'0986', N'SYSTEM', '20150831 19:05:51.457', N'', NULL, 1, 'ec1bb06e', N'上海分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'深圳' ), N'1086', N'SYSTEM', '20150831 19:05:51.460', N'', NULL, 1, '3257f5b0', N'深圳分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'北京' ), N'1186', N'SYSTEM', '20150831 19:05:51.467', N'', NULL, 1, '71e6608f', N'北京分公司', 0);


INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'苏州' ), N'1286', N'SYSTEM', '20150831 19:05:51.470', N'', NULL, 1, 'c017625d', N'江苏分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'东区' ), N'2586', N'SYSTEM', '20150831 19:05:51.480', N'', NULL, 1, '93711271', N'广东分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'中区' ), N'2586', N'SYSTEM', '20150831 19:05:51.480', N'', NULL, 1, '93711271', N'广东分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'西区' ), N'2586', N'SYSTEM', '20150831 19:05:51.480', N'', NULL, 1, '93711271', N'广东分公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'西区' ), N'2686', N'SYSTEM', '20150831 19:05:51.490', N'', NULL, 1, 'c0ed5d5e', N'佛山支公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'东区' ), N'2786', N'SYSTEM', '20150831 19:05:51.497', N'', NULL, 1, '2952f592', N'江门支公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'东区' ), N'2886', N'SYSTEM', '20150831 19:05:51.520', N'', NULL, 1, '9a9d4900', N'东莞支公司', 0);

INSERT INTO [dbo].[T_BRANCH] ( [DISTRICT_CODE], [BRANCH_NAME], [CREATED_BY], [CREATION_DATE], [MODIFIED_BY], [MODIFICATION_DATE], [STATUS], [TOKETN], [BRANCH_FULLNAME], [ORDERCODE])
VALUES ( (SELECT DISTRICT_CODE FROM [T_DISTRICT] WHERE DISTRICT_NAME=N'东区' ), N'2786', N'SYSTEM', '20150831 19:05:51.497', N'', NULL, 1, '78120d8e', N'江门支公司', 0);



